"""adding relationships to the tables

Revision ID: 4474f60d668e
Revises: 
Create Date: 2024-06-19 18:42:45.810145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4474f60d668e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['post'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
