"""added role to the user model

Revision ID: 634422678fe8
Revises: 6a7d8c0119a3
Create Date: 2024-06-22 15:00:16.790169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634422678fe8'
down_revision = '6a7d8c0119a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
