"""added a few columns to the user model and password hash generation, access token

Revision ID: 6a7d8c0119a3
Revises: db95f4e428f3
Create Date: 2024-06-22 12:56:55.064215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7d8c0119a3'
down_revision = 'db95f4e428f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('verified')
        batch_op.drop_column('date_created')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
