"""removed index on post(nullable=False)

Revision ID: 9c11539b38c1
Revises: 53d5350f0fba
Create Date: 2024-06-20 20:08:10.247356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c11539b38c1'
down_revision = '53d5350f0fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_index('post')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_index('post', ['post'], unique=True)

    # ### end Alembic commands ###
